update composer.json
While installation takes place, getting error that it looks for symfony/debug/ which is not installed.

Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /usr/local/zendphp7/var/apps/http/maintenance.zenddev.ftr.com/80/1.1.4_2334/vendor/symfony/console/Application.php:134